### ISSUE TITLE
Check format in CI is failing silently

### ISSUE THREAD

**Issue by J08nY** [shoracek/ossdev-02-468980#1]
The `git diff` call in the check format step of CI is failing for all runs silently.
See https://github.com/shoracek/ossdev-02-468980/blob/main/.github/workflows/c-cpp.yml#L23=
and https://github.com/shoracek/ossdev-02-468980/runs/5503586119?check_suite_focus=true
for the issue.

**Comment by shoracek** [comment]
No idea why this got broken. If the CI is run again it does not fail silently because of invalid object, see [1], [2].


[1]: https://github.com/shoracek/ossdev-02-468980/runs/6139667345?check_suite_focus=true
[2]: https://github.com/shoracek/ossdev-02-468980/runs/6139672507?check_suite_focus=true
